on: workflow_dispatch

name: "Check spelling, linting and links"

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    name: "Check Markdown files"
    steps:
    - uses: actions/checkout@master
    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile  # Remember to give an ID if you need the output filename
      name: Download the file
      with:
        url: "https://github.com/qir-alliance/.github/blob/main/workflow-templates/utils/md_lint_config.yml"
        target: .github/workflows/
    - run: |
        Get-ChildItem (Join-Path "workflow-templates" "utils" "problem-matchers") `
          | ForEach-Object {
            Write-Host "Adding matcher $_...";
            Write-Host "::add-matcher::$_";
          }
      shell: pwsh
    - name: markdownlint-cli
      # cspell:words nosborn
      uses: nosborn/github-action-markdown-cli@v2.0.0
      with:
        files: .
        config_file: "${{ steps.downloadfile.outputs.filename }}"
    - name: Markdown link check
      # cspell:words gaurav
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
      if: ${{ success() || failure() }}
