on: workflow_dispatch

name: "Check spelling, linting and links"

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    name: "Check Markdown files"
    steps:
    - uses: actions/checkout@master
    - run: |
        wget https://github.com/qir-alliance/.github/archive/refs/heads/main.zip -O clone.zip `
        && unzip clone.zip && mv .github-main out && rm clone.zip `
        && mv out/workflow-templates/utils/ utils && rm -r out
      shell: bash
    - run: |
        Get-ChildItem (Join-Path "utils" "problem-matchers") `
          | ForEach-Object {
            Write-Host "Adding matcher $_...";
            Write-Host "::add-matcher::$_";
          }
      shell: pwsh
    - name: markdownlint-cli
      # cspell:words nosborn
      uses: nosborn/github-action-markdown-cli@v2.0.0
      with:
        files: .
        config_file: 'utils/md_lint_config.yml'
    - name: Markdown link check
      # cspell:words gaurav
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
      if: ${{ success() || failure() }}
